var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';
OA_output['Sidebar 1'] += "<"+"span class=\"declare\">Advertisement<"+"/span><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4315__zoneid=40__OXLCA=1__cb=7556d8d203__oadest=http%3A%2F%2Fwww.usertesting.com%2F%3Futm_source%3DSmashingmag%26utm_medium%3Dbanners%26utm_campaign%3DSamashingBanners\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sneakpeek190x400_5.jpg&contenttype=jpeg\' width=\'190\' height=\'400\' alt=\'Easiest way to Usability Testing\' title=\'Easiest way to Usability Testing\' border=\'0\' /><"+"/a><"+"div id=\'beacon_7556d8d203\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4315&amp;campaignid=1481&amp;zoneid=40&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=7556d8d203\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';
OA_output['Medium Rectangle'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4285__zoneid=22__OXLCA=1__cb=dbed2d6b49__oadest=http%3A%2F%2Ffiverr.com%2Fcategories%2Fadvertising%2Forder%2Flatest%2Fpages%2F1%3F%26utm_source%3Ddt_my%26utm_term%3Da7300029%26utm_medium%3Delad-business-300X250_c-4%26utm_content%3Dc-4%26utm_campaign%3Dna_na\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=i-will-promote._300x250_2.jpg&contenttype=jpeg\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_dbed2d6b49\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4285&amp;campaignid=1464&amp;zoneid=22&amp;OACBLOCK=86400&amp;OACCAP=2&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=dbed2d6b49\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Comment spnsr'] = '';
OA_output['Comment spnsr'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4289__zoneid=26__OXLCA=1__cb=aaf016005b__oadest=http%3A%2F%2Fwww.formstack.com%2Fba-smashingmag%3Fba%3Dsmag%26utm_source%3Dsmag%26utm_medium%3Dbanner%26utm_campaign%3Dsmag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=formstack_new_468x90_21.jpg&contenttype=jpeg\' width=\'468\' height=\'90\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_aaf016005b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4289&amp;campaignid=1466&amp;zoneid=26&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=aaf016005b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Logo'] = '';

OA_output['Textad'] = '';
OA_output['Textad'] += "<"+"div id=\"textad\">(<"+"strong>Smashing\'s side note<"+"/strong>: Have you already bought the brand new <"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3452__zoneid=68__OXLCA=1__cb=fff2e463cc__oadest=http%3A%2F%2Fwww.smashingmagazine.com%2F2012%2F05%2F08%2Fthe-smashing-book-3-redesign-the-web-is-out%2F\" style=\"border-bottom: 1px solid rgba(0,0,0,0.1)\" >Smashing Book #3<"+"/a>? The book introduces new practical techniques and a whole new mindset for progressive Web design. <"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3452__zoneid=68__OXLCA=1__cb=fff2e463cc__oadest=http%3A%2F%2Fwww.smashingmagazine.com%2F2012%2F05%2F08%2Fthe-smashing-book-3-redesign-the-web-is-out%2Fhttp%3A%2F%2Fwww.smashingbook.com\" target=\"_self\">Get your book today!<"+"/a>)<"+"div id=\'beacon_fff2e463cc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3452&amp;campaignid=1018&amp;zoneid=68&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;cb=fff2e463cc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Sidebar Special'] = '';
OA_output['Sidebar Special'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4172__zoneid=72__OXLCA=1__cb=98600fa418__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com420c\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=420x200_cirlcles_new.png&contenttype=png\' width=\'420\' height=\'200\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_98600fa418\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4172&amp;campaignid=1422&amp;zoneid=72&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=98600fa418\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL'] = '';
OA_output['Sponsor XXL'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4287__zoneid=77__OXLCA=1__cb=5f179fadd5__oadest=http%3A%2F%2Fwww.psd2html.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=p2h_410x125_7_10_1.png&contenttype=png\' width=\'410\' height=\'125\' alt=\'PSD2HTML.com\' title=\'PSD2HTML.com\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4287__zoneid=77__OXLCA=1__cb=5f179fadd5__oadest=http%3A%2F%2Fwww.psd2html.com%2F\' target=\'_blank\'>PSD2HTML.com<"+"/a><"+"div id=\'beacon_5f179fadd5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4287&amp;campaignid=1458&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=5f179fadd5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 1'] = '';
OA_output['VIS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4213__zoneid=70__OXLCA=1__cb=94a7af371c__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_ms_200-125.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'PSD to HTML\' title=\'PSD to HTML\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4213__zoneid=70__OXLCA=1__cb=94a7af371c__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'>PSD to HTML<"+"/a><"+"div id=\'beacon_94a7af371c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4213&amp;campaignid=135&amp;zoneid=70&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=94a7af371c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3738__zoneid=24__OXLCA=1__cb=0cf262c804__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200roshlp\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_cirlcles_new.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Create free stunning websites!\' title=\'Create free stunning websites!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3738__zoneid=24__OXLCA=1__cb=0cf262c804__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200roshlp\' target=\'_blank\'>Create free stunning sites!<"+"/a><"+"div id=\'beacon_0cf262c804\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3738&amp;campaignid=130&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=0cf262c804\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4244__zoneid=24__OXLCA=1__cb=ae57440ebb__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=project-mgt-1(200x125)_13.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4244__zoneid=24__OXLCA=1__cb=ae57440ebb__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_ae57440ebb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4244&amp;campaignid=1447&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=ae57440ebb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4207__zoneid=24__OXLCA=1__cb=2c5c7e0217__oadest=http%3A%2F%2Fwww.zoho.com%2Fcreator%2Fonline-form-builder%2F%3Futm_source%3DSmashing-Mag%26utm_medium%3Dbanner%26utm_content%3Donlineform-brand%26utm_campaign%3DSmashing-Mag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=zohocreator-sm2_2.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Create Online Forms For Free\' title=\'Create Online Forms For Free\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4207__zoneid=24__OXLCA=1__cb=2c5c7e0217__oadest=http%3A%2F%2Fwww.zoho.com%2Fcreator%2Fonline-form-builder%2F%3Futm_source%3DSmashing-Mag%26utm_medium%3Dbanner%26utm_content%3Donlineform-brand%26utm_campaign%3DSmashing-Mag\' target=\'_blank\'>Create Online Forms For Free<"+"/a><"+"div id=\'beacon_2c5c7e0217\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4207&amp;campaignid=1436&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=2c5c7e0217\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"script language=\"JavaScript\" type=\"text/javascript\" src=\"http://view.atdmt.com/SHS/jview/348574350/direct/01?click=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4303__zoneid=24__OXLCA=1__cb=34456d325b__oadest=\">\n";
OA_output['spnsr ROS 4'] += "<"+"/script><"+"noscript><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4303__zoneid=24__OXLCA=1__cb=34456d325b__oadest=http%3A%2F%2Fclk.atdmt.com%2FSHS%2Fgo%2F348574350%2Fdirect%2F01%2F\" target=\"_blank\"><"+"img border=\"0\" src=\"http://view.atdmt.com/SHS/view/348574350/direct/01/\" /><"+"/a><"+"/noscript>\n";
OA_output['spnsr ROS 4'] += "<"+"br>\n";
OA_output['spnsr ROS 4'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4303__zoneid=24__OXLCA=1__cb=34456d325b__oadest=http%3A%2F%2Fwww.shutterstock.com%2F%3Fsid%3DSMSHM1004%26pl%3Dsmashingmagazine-200x125%26utm_medium%3Dtext_link\" target=\"_blank\">Royalty-Free Stock Images<"+"/a><"+"div id=\'beacon_34456d325b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4303&amp;campaignid=1475&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;cb=34456d325b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=fd294cd02d__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-dt-2.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Premium Web Templates\' title=\'Premium Web Templates\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=fd294cd02d__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'>Premium Web Templates<"+"/a><"+"div id=\'beacon_fd294cd02d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=2877&amp;campaignid=1026&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=fd294cd02d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 6'] = '';
OA_output['spnsr ROS 6'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4085__zoneid=24__OXLCA=1__cb=f31b4735d3__oadest=https%3A%2F%2Fwww.zoho.com%2Finvoice%2Flp%2Fzoho-invoice-time-tracking-software.html%3Futm_source%3Dsmashingmagazine%26utm_medium%3Dbanner%26utm_campaign%3DInvoiceBannerTimeTracking\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=zoho_invoice_200x125_12.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Now with App for Invoice\' title=\'Now with App for Invoice\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4085__zoneid=24__OXLCA=1__cb=f31b4735d3__oadest=https%3A%2F%2Fwww.zoho.com%2Finvoice%2Flp%2Fzoho-invoice-time-tracking-software.html%3Futm_source%3Dsmashingmagazine%26utm_medium%3Dbanner%26utm_campaign%3DInvoiceBannerTimeTracking\' target=\'_blank\'>Now with App for Invoice<"+"/a><"+"div id=\'beacon_f31b4735d3\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4085&amp;campaignid=1413&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=f31b4735d3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=938__zoneid=24__OXLCA=1__cb=5c0dfffea2__oadest=http%3A%2F%2Fwww.templatesold.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=tsold-200x125-dark_7.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Premium Blog Themes\' title=\'Premium Blog Themes\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=938__zoneid=24__OXLCA=1__cb=5c0dfffea2__oadest=http%3A%2F%2Fwww.templatesold.com\' target=\'_blank\'>Premium Blog Themes<"+"/a><"+"div id=\'beacon_5c0dfffea2\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=938&amp;campaignid=466&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=5c0dfffea2\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';
OA_output['spnsr ROS 8'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4294__zoneid=24__OXLCA=1__cb=efeb90dbe7__oadest=http%3A%2F%2Fhowinteractiveconference.com%2F%3Futm_source%3DSmashingMag%26utm_medium%3D200x125July16EB%26utm_campaign%3DAdsonSmashingMag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=73643-200x125eb_smashing.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Move from print to digital design\' title=\'Move from print to digital design\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4294__zoneid=24__OXLCA=1__cb=efeb90dbe7__oadest=http%3A%2F%2Fhowinteractiveconference.com%2F%3Futm_source%3DSmashingMag%26utm_medium%3D200x125July16EB%26utm_campaign%3DAdsonSmashingMag\' target=\'_blank\'>Move from print to digital design<"+"/a><"+"div id=\'beacon_efeb90dbe7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4294&amp;campaignid=1471&amp;zoneid=24&amp;OACBLOCK=86400&amp;OACCAP=2&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=efeb90dbe7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 9'] = '';
OA_output['spnsr ROS 9'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3415__zoneid=24__OXLCA=1__cb=3005d77f01__oadest=http%3A%2F%2Fwww.freshbooks.com%3Fref%3D378\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=0805-freshbooks-200x125_5.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Look Professional with FreshBooks!\' title=\'Look Professional with FreshBooks!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3415__zoneid=24__OXLCA=1__cb=3005d77f01__oadest=http%3A%2F%2Fwww.freshbooks.com%3Fref%3D378\' target=\'_blank\'>Online Invoicing for Freelancers<"+"/a><"+"div id=\'beacon_3005d77f01\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3415&amp;campaignid=1208&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=3005d77f01\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4051__zoneid=24__OXLCA=1__cb=5ff08e7a63__oadest=http%3A%2F%2Fbit.ly%2FKTUbsF\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ds-200-125.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Top quality free sets!\' title=\'Top quality free sets!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4051__zoneid=24__OXLCA=1__cb=5ff08e7a63__oadest=http%3A%2F%2Fbit.ly%2FKTUbsF\' target=\'_blank\'>Top quality free sets!<"+"/a><"+"div id=\'beacon_5ff08e7a63\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4051&amp;campaignid=1381&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=5ff08e7a63\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4291__zoneid=24__OXLCA=1__cb=aed61f7545__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=typekit-ad-200x125-1_6.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Web fonts with Typekit\' title=\'Web fonts with Typekit\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4291__zoneid=24__OXLCA=1__cb=aed61f7545__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'>Web fonts with Typekit<"+"/a><"+"div id=\'beacon_aed61f7545\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4291&amp;campaignid=1468&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=aed61f7545\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"div id=\"nowspotsbanner\"><"+"!-- BEGIN JS TAG - [Smashing Magazine] - Default <"+" - DO NOT MODIFY -->\n";
OA_output['spnsr ROS 12'] += "<"+"SCRIPT SRC=\"http://ib.adnxs.com/ttj?id=795177&pubclick=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3836__zoneid=24__OXLCA=1__cb=81497354c1__oadest=\" TYPE=\"text/javascript\"><"+"/SCRIPT>\n";
OA_output['spnsr ROS 12'] += "<"+"!-- END TAG -->\n";
OA_output['spnsr ROS 12'] += "<"+"br>\n";
OA_output['spnsr ROS 12'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3836__zoneid=24__OXLCA=1__cb=81497354c1__oadest=http%3A%2F%2Fwww.perfectaudience.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3Dundertext%26utm_campaign%3Ddeadsimple\" target=\"_blank\">$49 Retargeting for Developers<"+"/a><"+"div id=\'beacon_81497354c1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3836&amp;campaignid=1341&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;cb=81497354c1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['spnsr ROS 12'] += "<"+"style type=\"text/css\"><"+"!--\n";
OA_output['spnsr ROS 12'] += "#nowspotsbanner img {\n";
OA_output['spnsr ROS 12'] += "display: none;\n";
OA_output['spnsr ROS 12'] += "}\n";
OA_output['spnsr ROS 12'] += "#nowspotsbanner a img {\n";
OA_output['spnsr ROS 12'] += "display: inline;\n";
OA_output['spnsr ROS 12'] += "}\n";
OA_output['spnsr ROS 12'] += "#nowspotsbanner iframe {\n";
OA_output['spnsr ROS 12'] += "display: none;\n";
OA_output['spnsr ROS 12'] += "}\n";
OA_output['spnsr ROS 12'] += "--><"+"/style>\n";
OA_output['spnsr ROS 13'] = '';
OA_output['spnsr ROS 13'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4288__zoneid=24__OXLCA=1__cb=9ee3da48cf__oadest=http%3A%2F%2Fwww.formstack.com%2Fba-smashingmag%3Fba%3Dsmag%26utm_source%3Dsmag%26utm_medium%3Dbanner%26utm_campaign%3Dsmag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=formstack_new_200x125_22.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Drag and Drop Form Builder\' title=\'Drag and Drop Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4288__zoneid=24__OXLCA=1__cb=9ee3da48cf__oadest=http%3A%2F%2Fwww.formstack.com%2Fba-smashingmag%3Fba%3Dsmag%26utm_source%3Dsmag%26utm_medium%3Dbanner%26utm_campaign%3Dsmag\' target=\'_blank\'>Drag and Drop Form Builder<"+"/a><"+"div id=\'beacon_9ee3da48cf\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4288&amp;campaignid=1465&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=9ee3da48cf\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 14'] = '';
OA_output['spnsr ROS 14'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4214__zoneid=24__OXLCA=1__cb=6c1272b995__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\" target=\"_blank\"><"+"img src=\"http://statisches.auslieferung.commindo-media-ressourcen.de/jotform-smashing-banner.jpg\" width=\"200\" height=\"125\"><"+"/a><"+"br />\n";
OA_output['spnsr ROS 14'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4214__zoneid=24__OXLCA=1__cb=6c1272b995__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dlink%26utm_content%3Donline%252Bform%252Bbuilder%26utm_campaign%3Dsmashing\" target=\"_blank\">Online Form Builder<"+"/a><"+"div id=\'beacon_6c1272b995\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4214&amp;campaignid=1440&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;cb=6c1272b995\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 15'] = '';
OA_output['spnsr ROS 15'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3739__zoneid=24__OXLCA=1__cb=94d8b12fe4__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200cpchlp\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_cirlcles_new_2.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Create free stunning websites!\' title=\'Create free stunning websites!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=3739__zoneid=24__OXLCA=1__cb=94d8b12fe4__oadest=http%3A%2F%2Fwww.wix.com%2Fhtml5%2Fwebsites_400%3Futm_campaign%3Dma_smashingmagazine.com%26experiment_id%3Dma_smashingmagazine.com200cpchlp\' target=\'_blank\'>Create free stunning sites!<"+"/a><"+"div id=\'beacon_94d8b12fe4\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=3739&amp;campaignid=250&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=94d8b12fe4\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 16'] = '';
OA_output['spnsr ROS 16'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4310__zoneid=24__OXLCA=1__cb=066d95bb5d__oadest=http%3A%2F%2Fwww.usertesting.com%2F%3Futm_source%3DSmashingmag%26utm_medium%3Dbanners%26utm_campaign%3DSamashingBanners\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=girl200x125_11.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Easiest way to Usability Testing\' title=\'Easiest way to Usability Testing\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4310__zoneid=24__OXLCA=1__cb=066d95bb5d__oadest=http%3A%2F%2Fwww.usertesting.com%2F%3Futm_source%3DSmashingmag%26utm_medium%3Dbanners%26utm_campaign%3DSamashingBanners\' target=\'_blank\'>Easiest way to Usability Testing<"+"/a><"+"div id=\'beacon_066d95bb5d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4310&amp;campaignid=1480&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2008%2F06%2F18%2Fhand-drawing-style-in-modern-web-design-volume-2%2F%23more-479&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2Ftag%2Fdrawing%2F&amp;cb=066d95bb5d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Specials'] = '';

